### ISSUE TITLE
White screen on raspberry pi boot up

### ISSUE THREAD

**Issue by charlieprynn** [nopnop2002/ili9325_rpi#24]
Hi,

My screen is constantly white, with the back light on. Even when running the demos.

Can you tell which model of board I have?
![img_0146](https://user-images.githubusercontent.com/2809503/42645298-90ce7d86-85f5-11e8-8f7e-814ae3a59d23.jpeg)
![img_0144](https://user-images.githubusercontent.com/2809503/42645603-5f95abbc-85f6-11e8-92fc-0431f8ec43f6.jpeg)

**Comment by nopnop2002** [comment]
Please use this tool.

https://github.com/nopnop2002/lcd_id

And check this page.

http://domoticx.com/arduino-shield-2-4-tft-lcd-touch/

**Comment by charlieprynn** [comment]
The output from LCD_ID, I can't quite identify which model I have?
```
Read Registers on MCUFRIEND UNO shield
controllers either read as single 16-bit
e.g. the ID is at readReg(0)
or as a sequence of 8-bit values
in special locations (first is dummy)
reg(0x0000) 00 01	ID: ILI9320, ILI9325, ILI9335, ...
reg(0x0004) 00 00 00 00	Manufacturer ID
reg(0x0009) 00 00 00 00 00	Status Register
reg(0x000a) 00 01	Get Powsr Mode
reg(0x000c) 00 01	Get Pixel Format
reg(0x0061) 00 01	RDID1 HX8347-G
reg(0x0062) 00 01	RDID2 HX8347-G
reg(0x0063) 00 01	RDID3 HX8347-G
reg(0x0064) 00 01	RDID1 HX8347-A
reg(0x0065) 00 01	RDID2 HX8347-A
reg(0x0066) 00 01	RDID3 HX8347-A
reg(0x0067) 00 01	RDID Himax HX8347-A
reg(0x0070) 00 01	Panel Himax HX8347-A
reg(0x00a1) 00 01 00 01 00	RD_DDB SSD1963
reg(0x00b0) 00 01	RGB Interface Signal Control
reg(0x00b4) 00 01	Inversion Control
reg(0x00b6) 00 01 00 01 00	Display Control
reg(0x00b7) 00 01	Entry Mode Set
reg(0x00bf) 00 01 00 01 00 01	ILI9481, HX8357-B
reg(0x00c0) 00 01 00 01 00 01 00 01 00	Panel Control
reg(0x00c8) f8 00 f8 00 f8 00 f8 00 f8 00 f8 00 f8	GAMMA
reg(0x00cc) 00 01	Panel Control
reg(0x00d0) 00 01 00	Power Control
reg(0x00d2) f8 00 f8 00 f8	NVM Read
reg(0x00d3) 00 01 00 01	ILI9341, ILI9488
reg(0x00da) 00 01	RDID1
reg(0x00db) 00 01	RDID2
reg(0x00dc) 00 01	RDID3
reg(0x00e0) 00 01 00 01 00 01 00 01 00 01 00 01 00 01 00 01	GAMMA-P
reg(0x00e1) 00 01 00 01 00 01 00 01 00 01 00 01 00 01 00 01	GAMMA-N
reg(0x00ef) 00 01 00 01 00 01	ILI9327
reg(0x00f2) 00 01 00 01 00 01 00 01 00 01 00 01	Adjust Control 2
reg(0x00f6) 00 01 00 01	Interface Control
```

**Comment by nopnop2002** [comment]
Your TFT is TFT no one knows.

**Comment by charlieprynn** [comment]
Does that I'm SOL?

**Comment by nopnop2002** [comment]
It's the same outward appearance, but mcufriend has a lot of variations.

No one can use some of these.

**Comment by fisht99** [comment]
Hi there.

My screen is also white although it does flash during the demo.

I am using R61509V tft 3.0" and Raspberrypi 3

e.g. the ID is at readReg(0)
or as a sequence of 8-bit values
in special locations (first is dummy)
reg(0x0000) b5 09       ID: ILI9320, ILI9325, ILI9335, ...
reg(0x0004) 00 00 00 00 Manufacturer ID
reg(0x0009) 00 01 00 01 00      Status Register
reg(0x000a) 00 00       Get Powsr Mode
reg(0x000c) 00 00       Get Pixel Format
reg(0x0061) 00 00       RDID1 HX8347-G
reg(0x0062) 00 00       RDID2 HX8347-G
reg(0x0063) 00 00       RDID3 HX8347-G
reg(0x0064) 00 00       RDID1 HX8347-A
reg(0x0065) 00 00       RDID2 HX8347-A
reg(0x0066) 00 00       RDID3 HX8347-A
reg(0x0067) 00 00       RDID Himax HX8347-A
reg(0x0070) 00 00       Panel Himax HX8347-A
reg(0x00a1) 00 00 00 00 00      RD_DDB SSD1963
reg(0x00b0) 00 00       RGB Interface Signal Control
reg(0x00b4) 00 00       Inversion Control
reg(0x00b6) 00 00 00 00 00      Display Control
reg(0x00b7) 00 00       Entry Mode Set
reg(0x00bf) 00 00 00 00 00 00   ILI9481, HX8357-B
reg(0x00c0) 00 00 00 00 00 00 00 00 00  Panel Control
reg(0x00c8) 00 00 00 00 00 00 00 00 00 00 00 00 00      GAMMA
reg(0x00cc) 00 00       Panel Control
reg(0x00d0) 00 00 00    Power Control
reg(0x00d2) 00 00 00 00 00      NVM Read
reg(0x00d3) 00 00 00 00 ILI9341, ILI9488
reg(0x00da) 00 00       RDID1
reg(0x00db) 00 00       RDID2
reg(0x00dc) 00 00       RDID3
reg(0x00e0) 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     GAMMA-P
reg(0x00e1) 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     GAMMA-N
reg(0x00ef) 00 00 00 00 00 00   ILI9327
reg(0x00f2) 00 00 00 00 00 00 00 00 00 00 00 00 Adjust Control 2
reg(0x00f6) 00 00 00 00 Interface Control

**Comment by nopnop2002** [comment]
The R61509V is a little different.

My R61509V has a regulator.
Normally, a TFT with a regulator works at 5V, but my R61509V doesn't work unless I supply both 5V and 3.3V.

It's mine.
```
$ gpio -v
gpio version: 2.50
Copyright (c) 2012-2018 Gordon Henderson
This is free software with ABSOLUTELY NO WARRANTY.
For details type: gpio -warranty

Raspberry Pi Details:
  Type: Pi 2, Revision: 01, Memory: 1024MB, Maker: Sony
  * Device tree is enabled.
  *--> Raspberry Pi 2 Model B Rev 1.1
  * This Raspberry Pi supports user-level GPIO access.


$ uname -a
Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

```

**Comment by fisht99** [comment]
Thank you for your reply.

I have tried 5v as well and still doesn't work correctly. However the screen does flash momentarily with 5v and you can see the colour bars briefly.

I am curious how to hookup both 5v and 3v to the board. are you able to share your diagram?

Thanks again for your support and community contribution.

**Comment by nopnop2002** [comment]
This is Mine.
I made an adapter.

Orange is 3.3V.
Yellow is 5V.
White is GND.

![IMG_0316](https://user-images.githubusercontent.com/6020549/79841568-94344800-83f2-11ea-91ad-b8e0f74327d2.JPG)

**Comment by fisht99** [comment]
Hi there

Can you specify what pins on the tft you connect the 3.3 and 5v?

this is my tft
![Scan from 2020-04-21 06_21_28 PM](https://user-images.githubusercontent.com/25100632/79843006-fd20bd80-83fc-11ea-9179-b55fedfee4e7.jpg)

**Comment by nopnop2002** [comment]
This is my TFT.
![IMG_0319](https://user-images.githubusercontent.com/6020549/79845326-d6ac5380-83f7-11ea-926b-f0e00b047dc0.jpg)

**Comment by fisht99** [comment]
Thanks
I think mine could be faulty. i will just buy another

**Comment by nopnop2002** [comment]
The latest version officially supports OPEN-SMART R61509V 16Pin-Parallel.
