### ISSUE TITLE
Use as main screen

### ISSUE THREAD

**Issue by ElectroBoyCodes** [nopnop2002/ili9325_rpi#37]

**Comment by nopnop2002** [comment]
Hello

What is main screen?

/dev/fb0 looks like a Frame Buffer Device.





Frame Buffer Devive and Parallel TFT have completely different resolutions.

**Comment by ElectroBoyCodes** [comment]
> What is main screen?

The screen that comes on the monitor

> /dev/fb0 looks like a Frame Buffer Device.

I want to copy that to the screen

> Frame Buffer Devive and Parallel TFT have completely different resolutions.

I know, but i once used the lcd with another lib which i cant find anymore

**Comment by ElectroBoyCodes** [comment]
I tried to make the framebuffer but:
``
pi@berrypi0:~ $  sudo modprobe flexfb width=480 height=320 buswidth=8 init=\
> -1,0x01,-2,5,\
> -1,0xD0,0x07,0x42,0x18,\
> -1,0xD1,0x00,0x07,0x18,\
> -1,0xD2,0x01,0x02,\
> -1,0xC0,0x10,0x3B,0x00,0x02,0x11,\
> -1,0xC5,0x03,\
> -1,0x36,0x28,\
> -1,0x3A,0x55,\
> -1,0x11,-2,120,\
> -1,0x29,-2,20,\
> -3
modprobe: FATAL: Module flexfb not found in directory /lib/modules/5.10.103+
``

**Comment by nopnop2002** [comment]
https://github.com/nopnop2002/Raspberry-ili9325/wiki

**Comment by ElectroBoyCodes** [comment]
> https://github.com/nopnop2002/Raspberry-ili9325/wiki

That is what i followed, i think i will use another tft lib that makes the FrameBuffer on its own

**Comment by ElectroBoyCodes** [comment]
That also does not work

**Comment by nopnop2002** [comment]
If you select the wrong LCD driver, it will not work properly.

I have purchased more than 30 TFTs in the past, but only one correct piece of information.


The information provided by sellers on Ebay or AliExpress is largely incorrect.
You waste time if you don't choose the right driver.
There are many variations of the 2.4 inch shield.

http://domoticx.com/arduino-shield-2-4-tft-lcd-touch/



You can use this to find out your driver.
This is for Arduino UNO.

https://github.com/prenticedavid/MCUFRIEND_kbv/tree/master/examples/LCD_ID_readreg



Here is my collection.

https://github.com/nopnop2002/esp-idf-parallel-tft/tree/main/lcd_id

**Comment by ElectroBoyCodes** [comment]
> If you select the wrong LCD driver, it will not work properly.
> 
> I have purchased more than 30 TFTs in the past, but only one correct piece of information.
> 
> The information provided by sellers on Ebay or AliExpress is largely incorrect. You waste time if you don't choose the right driver. There are many variations of the 2.4 inch shield.
> 
> http://domoticx.com/arduino-shield-2-4-tft-lcd-touch/
> 
> You can use this to find out your driver. This is for Arduino UNO.
> 
> https://github.com/prenticedavid/MCUFRIEND_kbv/tree/master/examples/LCD_ID_readreg
> 
> Here is my collection.
> 
> https://github.com/nopnop2002/esp-idf-parallel-tft/tree/main/lcd_id

it did not work because im unable to install it

**Comment by ElectroBoyCodes** [comment]
Also, i have the ILI9486 3.5'' one, not the 2.4''

**Comment by nopnop2002** [comment]
ILI9486 has a different initialization code.

https://github.com/nopnop2002/esp-idf-parallel-tft/blob/main/components/tft_library/ili9486.c

**Comment by ElectroBoyCodes** [comment]
> ILI9486 has a different initialization code.
> 
> https://github.com/nopnop2002/esp-idf-parallel-tft/blob/main/components/tft_library/ili9486.c

Sorry for the late responce the comment is not getting sent, but anyways, the problem is that im using https://github.com/sammyizimmy/ili9341 which is a module. But, im getting this error: 

```
pi@berrypi0:~/ili9341 $ make
make -C /lib/modules/5.15.32+/build M=/home/pi/ili9341 modules
make[1]: *** /lib/modules/5.15.32+/build: No such file or directory.  Stop.
make: *** [Makefile:4: all] Error 2
pi@berrypi0:~/ili9341 $
```

So im unable to build the module so im unable to use it

**Comment by nopnop2002** [comment]
You need to specify the driver as an argument to make.

**Comment by ElectroBoyCodes** [comment]
> You need to specify the driver as an argument to make.

What do you mean

**Comment by nopnop2002** [comment]
make hogehoge

Please read the README.

**Comment by ElectroBoyCodes** [comment]
> make hogehoge

ok, i will try

**Comment by ElectroBoyCodes** [comment]
@nopnop2002 
pi@berrypi0:~ $ make hogehoge
make: *** No rule to make target 'hogehoge'.  Stop.
pi@berrypi0:~ $

**Comment by nopnop2002** [comment]
Please read the README.

**Comment by ElectroBoyCodes** [comment]
> Please read the README.

Im using this one, not the one you made:
https://github.com/sammyizimmy/ili9341/

**Comment by nopnop2002** [comment]
This is not my repo.

This is out topic.

**Comment by ElectroBoyCodes** [comment]
> This is not my repo.
> 
> This is out topic.

Ok, can you help me with your repo? the FrameBuffer one you told in the wiki no longer works with the new linux release.

**Comment by ElectroBoyCodes** [comment]
The error is: modprobe: FATAL: Module flexfb not found in directory /lib/modules/5.15.32+

**Comment by nopnop2002** [comment]
>Module flexfb not found in directory /lib/modules/5.15.32+


This is not a bug in this repo.

Please search on the internet.

**Comment by ElectroBoyCodes** [comment]
> > Module flexfb not found in directory /lib/modules/5.15.32+
> 
> This is not a bug in this repo.
> 
> Please search on the internet.

It is not a bug, the wiki is outdated, it got removed in the newer verions of the kernel due to rework in the gpio framework

**Comment by ElectroBoyCodes** [comment]
@nopnop2002 
Do you have an [overlay](https://github.com/notro/fbtft/wiki/FBTFT-RPI-overlays) for this display?

**Comment by nopnop2002** [comment]
No


It seem os problem


https://forums.raspberrypi.com/viewtopic.php?t=280676

**Comment by ElectroBoyCodes** [comment]
> It seem os problem
> 
> https://forums.raspberrypi.com/viewtopic.php?t=280676

What can i do now? Do you have any alternatives?

**Comment by nopnop2002** [comment]
OS problems can only be solved by the Raspberry Foundation

**Comment by ElectroBoyCodes** [comment]
> OS problems can only be solved by the Raspberry Foundation

Ok, any alternatives or this lib?

**Comment by nopnop2002** [comment]
It may work if you use an old OS.

**Comment by ElectroBoyCodes** [comment]
> It may work if you use an old OS.

I'm not in the mood to downgrade

**Comment by nopnop2002** [comment]
If so, you have no solution.

**Comment by ElectroBoyCodes** [comment]
> If so, you have no solution.

Not even others libs insted of this lib?

**Comment by nopnop2002** [comment]
>Not even others libs insted of this lib?

I do not understand the meaning.

Do you want to use framebuffer

Or do you want to use this library?

This library has nothing to do with the framebuffer.

**Comment by ElectroBoyCodes** [comment]
> > Not even others libs insted of this lib?
> 
> I do not understand the meaning.
> 

Im asking if you know any other lib as an aternative for this one

> Do you want to use framebuffer
>

If you or I or someone can get it to work, then yes!

> This library has nothing to do with the framebuffer.
>

Ok...?

**Comment by nopnop2002** [comment]
If you want to use a framebuffer, this library doesn't help at all.

This library doesn't use the framebuffer feature at all.

And I'm not familiar with framebuffers.

**Comment by ElectroBoyCodes** [comment]
> If you want to use a framebuffer, this library doesn't help at all.
> 
> This library doesn't use the framebuffer feature at all.

do you know anyother library that has framebuffer?

**Comment by nopnop2002** [comment]
The frame buffer is a function of the OS, not a library.

You need to understand what a framebuffer is.

**Comment by ElectroBoyCodes** [comment]
> The frame buffer is a function of the OS, not a library.
> 
> You need to understand what a framebuffer is.

I did understand, im asking for a tft lcd library that creates another framebuffer for the display

**Comment by nopnop2002** [comment]
You can find it with the following keywords

flexfb alternative

**Comment by ElectroBoyCodes** [comment]
> flexfb alternative

I'm unable to find...

**Comment by nopnop2002** [comment]
Here is the source.

https://github.com/notro/fbtft/blob/master/flexfb.c

You can find the problem.
You can find the cause of the problem
