### ISSUE TITLE
Pico support

### ISSUE THREAD

**Issue by ElectroBoyCodes** [nopnop2002/ili9325_rpi#38]
Micro py

**Comment by nopnop2002** [comment]
No
Pico is not Linux.

**Comment by ElectroBoyCodes** [comment]
I know, any plans on supporting it?

**Comment by nopnop2002** [comment]
I don't know.


Perhaps it can be easily developed by changing this.

https://github.com/prenticedavid/MCUFRIEND_kbv

**Comment by ElectroBoyCodes** [comment]
> I don't know.
> 
> Perhaps it can be easily developed by changing this.
> 
> https://github.com/prenticedavid/MCUFRIEND_kbv

ok
