### ISSUE TITLE
Can't use it as a main screen

### ISSUE THREAD

**Issue by N3KRoN** [nopnop2002/ili9325_rpi#40]
Good afternoon, there is a problem again. I can't make a screen with a framebuffer to display the retropie image there. 
I followed the instructions from the wiki (https://github.com/nopnop2002/Raspberry-ili9325/wiki/FrameBuffer-Setting-to-ILI9341), but the output is.
<img width="648" alt="Screen Shot 2022-05-02 at 12 27 55" src="https://user-images.githubusercontent.com/11051346/166213762-66e09ccc-78b4-4d37-991b-abd6cb2747e6.png">
I installed the driver according to these instructions, but it didn't work either https://wasa-labo.com/wp/

have kernel: 5.10.103

display ILI9341 and 26 pins raspberry

**Comment by N3KRoN** [comment]
I put an old version of retropie with a Linux kernel 4.14.98+ and it worked, but the FPS is too low and I can't rotate the screen 270 degree

https://user-images.githubusercontent.com/11051346/166237251-0a7fe6fb-e35b-4404-8150-1c7cb0280bae.mp4

s

**Comment by nopnop2002** [comment]
This is a flexfb issue.
Contact here.

https://github.com/notro/fbtft/issues

---


It doesn't make sense on the "main screen".
It is called "Frame Buffer console".
