### ISSUE TITLE
wiringpi problem

### ISSUE THREAD

**Issue by Nicolai-Holmgaard** [nopnop2002/ili9325_rpi#42]
Im getting a problem with wiringpi. It says it cant be found, and its not installed on my pi 3. I cant install it.
This is the error i get.
 make ILI9341
cc    -c -o driver/ili9225.o driver/ili9225.c
cc    -c -o driver/ili9320.o driver/ili9320.c
cc    -c -o driver/ili9325.o driver/ili9325.c
cc    -c -o driver/ili9327.o driver/ili9327.c
cc    -c -o driver/ili9341.o driver/ili9341.c
cc    -c -o driver/ili9342.o driver/ili9342.c
cc    -c -o driver/ili9481.o driver/ili9481.c
cc    -c -o driver/ili9486.o driver/ili9486.c
cc    -c -o driver/ili9488.o driver/ili9488.c
cc    -c -o driver/lgdp4532.o driver/lgdp4532.c
cc    -c -o driver/r61509.o driver/r61509.c
cc    -c -o driver/s6d1121.o driver/s6d1121.c
cc    -c -o driver/st7781.o driver/st7781.c
ar crv driver.a driver/ili9225.o driver/ili9320.o driver/ili9325.o driver/ili9327.o driver/ili9341.o driver/ili9342.o driver/ili9481.o driver/ili9486.o driver/ili9488.o driver/lgdp4532.o driver/r61509.o driver/s6d1121.o driver/st7781.o
a - driver/ili9225.o
a - driver/ili9320.o
a - driver/ili9325.o
a - driver/ili9327.o
a - driver/ili9341.o
a - driver/ili9342.o
a - driver/ili9481.o
a - driver/ili9486.o
a - driver/ili9488.o
a - driver/lgdp4532.o
a - driver/r61509.o
a - driver/s6d1121.o
a - driver/st7781.o
driver.a make success
cc    -c -o tjpgd2/decode_jpeg.o tjpgd2/decode_jpeg.c
cc    -c -o tjpgd2/tjpgd.o tjpgd2/tjpgd.c
ar crv jpeg.a tjpgd2/decode_jpeg.o tjpgd2/tjpgd.o
a - tjpgd2/decode_jpeg.o
a - tjpgd2/tjpgd.o
jpeg.a make success
cc    -c -o pngle/decode_png.o pngle/decode_png.c
cc    -c -o pngle/miniz.o pngle/miniz.c
cc    -c -o pngle/pngle.o pngle/pngle.c
ar crv png.a pngle/decode_png.o pngle/miniz.o pngle/pngle.o
a - pngle/decode_png.o
a - pngle/miniz.o
a - pngle/pngle.o
png.a make success
cc -o demo demo.c fontx.c tft_lib.c driver.a jpeg.a png.a -lwiringPi -lm -lpthread -DILI9341
demo.c:10:10: fatal error: wiringPi.h: No such file or directory
   10 | #include <wiringPi.h>
      |          ^~~~~~~~~~~~
compilation terminated.
tft_lib.c:6:10: fatal error: wiringPi.h: No such file or directory
    6 | #include <wiringPi.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:58: ILI9341] Error 1

**Comment by nopnop2002** [comment]
```
pi@raspberrypi ~ $ sudo apt install git                    
pi@raspberrypi ~ $ git clone https://github.com/WiringPi/WiringPi
pi@raspberrypi ~ $ cd WiringPi
pi@raspberrypi ~ $ sudo ./build
pi@raspberrypi ~ $ gpio -v
```

**Comment by nopnop2002** [comment]
Since your problem is an installation issue, not a problem with this project, we will close this issue.

And you are advised to read the README carefully.

Easy questions are a waste of each other's time.

**Comment by Nicolai-Holmgaard** [comment]
Thank you, that helped. I will try to research better next time...
